---
title: "R 'n Py Logistic regression and bootstrapping"
layout: post
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Non-glm definition of logistic regression
$\beta_0 + \beta_1 x$

```{r, engine='python', fig.path="figures/pypy.png"}
import numpy as numpy
from numpy import add
from numpy import random
from numpy import multiply
from sklearn import linear_model
import matplotlib.pyplot as plt
import scipy
#inverse logit transform
def plogis(x, a, b):
    exp_pred = numpy.exp( add(a, multiply(b,x))) 
    return(exp_pred / (exp_pred + 1))

#true parameters
a = 2
b = -0.2
n = 100

#generate covariate(s)
x = sorted(numpy.random.normal(loc = 0, scale = 10, size = n))
x_arr = numpy.asarray(x).reshape(-1, 1)

sim_p = plogis( x = x_arr, a = a, b = b)

log_data = []
for p in sim_p:
    bern = numpy.random.binomial(n = 1, p = p)
    log_data.append(bern)
    
logreg = linear_model.LogisticRegression()
logreg.fit(x_arr, log_data)

def print_mod( intercept, coef):
    print('term', 'real', 'estimated')
    print('coef', b, intercept)
    print('Intercept', a, coef)


print_mod(logreg.coef_[0][0], logreg.intercept_[0])

pred = plogis( x_arr, a, b)

log_plot = plt.plot(x_arr, log_data, "ro")
plt.ylim([-0.1,1.1])
plt.plot(x_arr, sim_p, color = "r")
plt.plot(x_arr, pred, color = "b", linestyle = "dashed")
plt.ylabel("p( y = 1)")
plt.xlabel("x")
plt.show()

a_s = []
b_s = []
sims = 1000

dat_idx = numpy.asarray(list(range(1, len(x_arr))))

for i in range(1, sims):
    boot_idx = numpy.random.choice(dat_idx, len(x_arr), replace = True)

    boot_x = []
    boot_y = []

    for i in boot_idx:
        boot_x.append(x_arr[i])
        boot_y.append(log_data[i])
    
    boot_x = numpy.asarray(boot_x)

    logreg_boot = linear_model.LogisticRegression()
    logreg_boot.fit(boot_x, boot_y)

    a_s.append(logreg_boot.intercept_[0])
    b_s.append(logreg_boot.coef_[0][0])
    
    
    
for i in range(1, len(a_s)):
    pred = plogis( x_arr, a_s[i], b_s[i])
    plt.plot(x_arr, pred, color = '0.5')
    
plt.plot(x_arr, sim_p, color = "m", linewidth = 4)
plt.plot(x_arr, log_data, "bo")
plt.ylim([-0.1,1.1])
plt.ylabel("p( y = 1)")
plt.xlabel("x")
plt.show()

plt.hist(b_s)
plt.xlabel("b")
plt.ylabel("frequency")
plt.show()
print("mean = ",scipy.mean(b_s))
print("standard dev = ", scipy.std(b_s))
print("95% iqr" , numpy.percentile(b_s, q = [2.5, 97.5]))


plt.hist(a_s)
plt.xlabel("a")
plt.ylabel("frequency")
plt.title("")
plt.show()
print("mean = ",scipy.mean(a_s))
print("standard dev = ", scipy.std(a_s))
print("95% iqr" , numpy.percentile(a_s, q = [2.5, 97.5]))

```


